version: '3.5'
services:
  gfs:
    build:
      context: ./
      dockerfile: Dockerfile_task
    container_name: yh-process-gfs
    restart: always
    env_file:
      - .env
    network_mode: host
    volumes:
      - ${API_VOLUME}:${API_VOLUME}
      - ${DATA_VOLUME}:${DATA_VOLUME}
    environment:
      - BASE=${API_VOLUME}
    entrypoint: [ "/bin/sh", "-c", "chmod +x ${API_VOLUME}/yh-process-gfs && ${API_VOLUME}/yh-process-gfs" ]

  download:
    build:
      context: ./
      dockerfile: Dockerfile_download
    container_name: yh-process-download
    restart: always
    env_file:
      - .env
    ports:
      - "9001:9001"
    network_mode: host
    volumes:
      - ${API_VOLUME}:${API_VOLUME}
      - ${DATA_VOLUME}:${DATA_VOLUME}
    environment:
      - BASE=${API_VOLUME}
    entrypoint: [ "/bin/sh", "-c", "chmod +x ${API_VOLUME}/yh-process-download && ${API_VOLUME}/yh-process-download --host=192.168.1.14 --port=9001" ]

